modLoader="javafml"
loaderVersion="[46,)"
license="Custom License"
[[mods]]
modId="glowlights"
version="1.0.0-1.20"
displayName="Glow Lights"
logoFile="pack.png"
credits="Thanks to KaupenJoe and his tutorials."
authors="TheBrewingMiner"

description='''

A lightweight mod aiming to make glow ink more useful with palatable blocks.

'''

[[dependencies.glowlights]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.glowlights]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"